### ISSUE TITLE
database setup 

### ISSUE THREAD

**Issue by eriggs0207** [Penitent0/little-esty-shop#42]
┆Issue is synchronized with this [Trello card](https://trello.com/c/NkagsXjT) by [Unito](https://www.unito.io)

**Comment by aleish-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [database setup ](https://trello.com/c/NkagsXjT/41-database-setup)

**Comment by aleish-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub API PRs](https://trello.com/c/0HMoY6Rg/1-github-api-prs)
